<?php
/**
 * Title: Carousel Element
 *
 * Description: Defines custom post type "carousel".
 *				Defines action to be done when element "carousel" is active.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsCarousel' ) ) {
	class CyberChimpsCarousel {

		protected static $instance;
		public $options;

		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}

		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			add_action( 'carousel_section', array( $this, 'render_display' ) );
			$this->options = get_option( 'cyberchimps_options' );
			add_action( 'init', array( $this, 'cyberchimps_init_carousel_post_type' ) );
		}

		//Define Custom post type
		function cyberchimps_init_carousel_post_type() {
			register_post_type( 'featured_posts',
				array(
					'labels' => array(
						'name' => __( 'Carousel', 'cyberchimps' ),
						'singular_name' => __( 'Posts', 'cyberchimps' )
					),
					'public' => true,
					'show_ui' => true, 
					'supports' => array('custom-fields', 'title'),
					'taxonomies' => array( 'carousel_categories'),
					'has_archive' => true,
					'menu_icon' => get_template_directory_uri() . '/cyberchimps/lib/images/custom-types/carousel.png',
					'rewrite' => array('slug' => 'slides')
				)
			);

			$labels = array(
				'name' => _x( 'Carousel Categories', 'taxonomy general name', 'cyberchimps' ),
				'singular_name' => _x( 'Carousel Catergory', 'taxonomy singular name', 'cyberchimps' ),
				'search_items' =>  __( 'Search Carousel', 'cyberchimps' ),
				'all_items' => __( 'All Carousels', 'cyberchimps' ),
				'parent_item' => __( 'Carousel Category', 'cyberchimps' ),
				'parent_item_colon' => __( 'Carousel Category:', 'cyberchimps' ),
				'edit_item' => __( 'Edit Carousel Category', 'cyberchimps' ), 
				'update_item' => __( 'Update Carousel Category', 'cyberchimps' ),
				'add_new_item' => __( 'Add New Carousel Category', 'cyberchimps' ),
				'new_item_name' => __( 'New Carousel Category Name', 'cyberchimps' ),
				'menu_name' => __( 'Carousel Category', 'cyberchimps' )
			);
			
			register_taxonomy( 'carousel_categories',array('featured_posts'), array(
				'public' => true,
				'show_in_nav_menus' => false,
				'hierarchical' => true,
				'labels' => $labels,
				'show_ui' => true
			));

			$meta_boxes = array();

			$mb = new Chimps_Metabox('Carousel', 'Featured Post Carousel', array('pages' => array('featured_posts')));
			$mb
				->tab( __( 'Featured Post Carousel Options', 'cyberchimps' ) )
					->single_image('post_image', __( 'Featured Post Image', 'cyberchimps' ), '')
					->text('post_url', __( 'Featured Post URL', 'cyberchimps' ), '')
					->reorder('reorder_id', __( 'Reorder Name', 'cyberchimps' ), 'Reorder Desc' )
				->end();
		}

		/**
		 * Puts markup for carousel
		 *
		 * @return void
		 */
		public function render_display() {
			
			// Get the default image of carousel
			$default = get_template_directory_uri() . apply_filters( 'cyberchimps_carousel_img', '/cyberchimps/lib/images/carousel.jpg' );
			
			// Initialize variable that holds markup string to be echoed
			$out = '';

			if ( is_page() ) {
				$customcategory = get_post_meta( get_the_ID(), 'carousel_category' , true );
			}
			else {
				if( isset( $this->options['carousel_categories'] ) ) {
					$customcategory_obj = get_term( $this->options['carousel_categories'], 'carousel_categories' );
					$customcategory = $customcategory_obj->slug;
				}
				else {
					$customcategory = '';
				}
			}
			?>
			<div id="container" class="row-fluid">
				<div id="carousel" class="es-carousel-wrapper">
					<div class="es-carousel">
					
						<?php
						$args = array(
							'numberposts'     		=> 50,
							'offset'          		=> 0,
							'carousel_categories'	=> $customcategory,
							'orderby'				=> 'post_date',
							'order'          		=> 'ASC',
							'post_type'       		=> 'featured_posts',
							'post_status'     		=> 'publish'
						);

						// HS set total posts so the loop can be finished correctly, this needs to be changed when we use get_posts()
						$carousel_posts = get_posts( $args );

						// If custom there is any post in custom post type carousel then display them
						if ( $carousel_posts ) {
							$out .= '<ul>';
							foreach( $carousel_posts as $post ) {
							
								/* Post-specific variables */
								$image = get_post_meta($post->ID, 'post_image', true);
								$link = ( get_post_meta($post->ID, 'post_url', true) != '' ) ? get_post_meta($post->ID, 'post_url', true) : get_post_meta($post->ID, 'post_image', true);
								$rel = ( $link == $image ) ? 'rel="cyberchimps-lightbox"' : '';
								$title = $post->post_title;
								
								// Set image to default if no image is supplied
								if ($image == '') {
									$image = $default;
								}

								$out .= '<li>';
								$out .= '<a href="'.$link.'" '.$rel.'><img src="'.$image.'" alt="'.$title.'" /></a>';
								$out .= '<div class="carousel_caption">'. $title .'</div>';
								$out .= '</li>';
							}
							$out .= '</ul>';
						}
						else {
							// If no posts are there in custom post type carosel then display default image 6 times
							$out .= '<ul>';
							$default_counter = 0;
							for( $default_counter = 0; $default_counter < 6; $default_counter++ ) {
								$out .= '<li>';
								$out .= '<a href="'.$default.'" rel="cyberchimps-lightbox"><img src="'.$default.'" alt="Post 1"/></a>';
								$out .= '<div class="carousel_caption">'. apply_filters( "cyberchimps_current_theme_name", "CyberChimps" ). '</div>';
								$out .= '</li>';
							}
							$out .= '</ul>';
						}

						echo $out;
						?>
				
					</div><!-- .es-carousel -->
				</div><!-- #carousel -->
			</div><!-- #container -->
		<?php
		}
	}
}
CyberChimpsCarousel::instance();