<?php
/**
 * Element Initializer
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Load style for elements
function cyberchimps_add_elements_scripts() {

	// Set path of library
	$path_lib = get_template_directory_uri() . '/elements/lib/';
	
	// Add JS for elastislide librarry to be used for carousel element.	
	wp_register_script( 'elastislide' , $path_lib . 'js/jquery.elastislide.js');
	wp_enqueue_script( 'elastislide', array( 'jquery', 'jquerypp' ) );
	
	wp_register_style( 'elements_style', $path_lib . 'css/elements.css' );
	wp_enqueue_style('elements_style');
	
	wp_register_style( 'jcarousel-skin', $path_lib . 'css/jcarousel/skin.css' );
	wp_enqueue_style( 'jcarousel-skin', array('bootstrap-responsive-style', 'bootstrap-style'), '1.0' ); 
	
	wp_register_script( 'elements_js', $path_lib . 'js/elements.js' );
	wp_enqueue_script( 'elements_js', array( 'jquery' ) );
}
add_action( 'wp_enqueue_scripts', 'cyberchimps_add_elements_scripts', 30 );

// Set path of element folder.
$path_elements = get_template_directory() . '/elements/';

// Load elements
require_once( $path_elements . 'widgets.php' );
require_once( $path_elements . 'breadcrumbs.php' );
require_once( $path_elements . 'callout.php' );
require_once( $path_elements . 'carousel.php' );
require_once( $path_elements . 'htmlbox.php' );
//require_once( $path_elements . 'magazine.php' );
require_once( $path_elements . 'pagination.php' );
require_once( $path_elements . 'portfolio.php' );
//require_once( $path_elements . 'product.php' );
require_once( $path_elements . 'slider.php' );
require_once( $path_elements . 'twitter-bar.php' );
require_once( $path_elements . 'recent-posts.php' );
require_once( $path_elements . 'boxes.php' );
//require_once( $path_elements . 'profile.php' );
//require_once( $path_elements . 'featured-posts.php' );

function cyberchimps_selected_elements() {
	$options = array(
			'boxes'					=> __( 'Boxes', 'cyberchimps' ),
			"callout_section"		=> __( 'Callout Section', 'cyberchimps' ),
			"carousel_section"		=> __( 'Carousel', 'cyberchimps' ),
			//'featured_posts'		=> __( 'Featured Posts', 'cyberchimps' ),
			'html_box'				=> __( 'HTML Box', 'cyberchimps' ),
			'page_slider'			=> __( 'iFeature Slider', 'cyberchimps' ),
			//'magazine'				=> __( 'Magazine', 'cyberchimps' ),
			'portfolio_pro'			=> __( 'Portfolio', 'cyberchimps' ),
			"blog_post_page"		=> __( 'Post Page', 'cyberchimps' ),
			//"product_element"		=> __( 'Product', 'cyberchimps' ),
			//"profile"				=> __( 'Profile', 'cyberchimps' ),
			'recent_posts'			=> __( 'Recent Posts', 'cyberchimps' ),
			"twitterbar_section"	=> __( 'Twitter Bar', 'cyberchimps' ),
			"widgets_section"		=> __( 'Widgets', 'cyberchimps' )	
		);
	return $options;
}
add_filter( 'cyberchimps_elements_draganddrop_options', 'cyberchimps_selected_elements', 2 );

//set defaults elements for page draga and drop
function cyberchimps_selected_page_elements() {
	$options = array(
			'boxes'					=> __( 'Boxes', 'cyberchimps' ),
			'breadcrumbs'			=> __( 'Breadcrumbs', 'cyberchimps' ),
			"callout_section"		=> __( 'Callout Section', 'cyberchimps' ),
			"carousel_section"		=> __( 'Carousel', 'cyberchimps' ),
			//'featured_posts'		=> __( 'Featured Posts', 'cyberchimps' ),
			'html_box'				=> __( 'HTML Box', 'cyberchimps' ),
			'page_slider'			=> __( 'iFeature Slider', 'cyberchimps' ),
			//'magazine'				=> __( 'Magazine', 'cyberchimps' ),
			'portfolio_pro'			=> __( 'Portfolio', 'cyberchimps' ),
			"page_section"			=> __( 'Page', 'cyberchimps' ),
			//"product_element"		=> __( 'Product', 'cyberchimps' ),
			//"profile"				=> __( 'Profile', 'cyberchimps' ),
			'recent_posts'			=> __( 'Recent Posts', 'cyberchimps' ),
			"twitterbar_section"	=> __( 'Twitter Bar', 'cyberchimps' ),
			"widgets_section"		=> __( 'Widgets', 'cyberchimps' )	
		);
	return $options;
}
add_filter( 'cyberchimps_elements_draganddrop_page_options', 'cyberchimps_selected_page_elements', 2 );