<?php
/**
 * Title: Magazine Element
 *
 * Description: Displays Latest posts in two/three columns box layout with optional wide posts
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

add_action( 'magazine', 'cyberchimps_magazine_element_content' );

// Defining contents of the magazine post element
function cyberchimps_magazine_element_content() {

	// Reset the query to avoid conflict
	wp_reset_query();

	// call globals
	global $post;	

	/****** Getting Magazine options starts ******/

	// If element is on page
	if( is_page() ) {

		// Getting number of columns
		$column_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_columns', true);

		// Getting number of rows
		$row_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_rows', true);

		// Getting wide post toglle option and number of wide posts
		$wide_post_toggle =  get_post_meta($post->ID, 'cyberchimps_magazine_wide_post_toggle', true);
		$wide_post_no = get_post_meta($post->ID, 'cyberchimps_magazine_no_of_wide_posts', true);
		$wide_post_no += 1;

		// Getting metadata toggle
		$meta_toggle = get_post_meta($post->ID, 'cyberchimps_magazine_meta_data_toggle', true);
		
		// Getting featured image toggle.
		$featured_post_toggle = get_post_meta($post->ID, 'cyberchimps_magazine_featured_image', true );
		
		// getting post categories
		$category = get_post_meta($post->ID, 'cyberchimps_magazine_category', true);
	}

	//If element is on blog
	elseif( is_home() ) {

		// Getting the cyberchmips options
		$options = get_option('cyberchimps_options');

		// Getting number of columns
		$column_no = $options['blog_magazine_no_of_columns'];
		
		// Getting number of rows
		$row_no = $options['blog_magazine_no_of_rows'];

		// Getting wide post toglle option and number of wide posts
		$wide_post_toggle =  $options['blog_magazine_wide_post'];
		$wide_post_no = $options['blog_magazine_no_of_wide_posts'];

		// Getting metadata toggle
		$meta_toggle = $options['blog_magazine_metadata'];
		
		// Getting featured image toggle.
		$featured_post_toggle = $options['blog_magazine_featured_image'];
		
		// getting post categories
		$category = cyberchimps_get_option( 'blog_magazine_category', "");
	}
	
	// change the span depending on number of columns
	$span = ( $column_no == 2 ) ? 'span6' : 'span4';
		
	/****** Getting Magazine options ends ******/
?>
	<div id="magazine_conatiner" class="row-fluid">
		<?php
		// Making the query to bring the magazine posts
		$page_number = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;
		$category = ( $category != 'all' ) ? $category : '';
		$post_no_total = ( $row_no * $column_no ) + ( $wide_post_toggle ? $wide_post_no : 0 );
		$magazine = new WP_Query(
								array(
									'paged'    			=> $page_number,
									'posts_per_page'	=> $post_no_total,
									'post_type'			=> 'post',
									'cat'				=> $category,
									'orderby'  			=> 'post_date',
									'order'    			=> 'desc'
									)
								);
		?>
		
		<div id="magazine" class="span9">
			<div class="row-fluid">
				
				<?php
				/* Initializing counters. */
				$counter_post = 0; 
				$counter_box = 0;
				$counter_wide = 0;

				if ($magazine -> have_posts()) {
					while ($magazine -> have_posts()) {
						$magazine -> the_post();
						if( $counter_post < ( $row_no * $column_no ) )
						{ ?>
							<div class="post_container box_post <?php echo $span; ?>">
								<div <?php post_class() ?> id="post-<?php the_ID(); ?>">
								
									<!-- Display Title -->
									<h2 class="posts_title"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h2>
									
									<!-- Display Thumbnail -->
									<?php
									if ( has_post_thumbnail() && $featured_post_toggle ) {
										echo '<div class="featured-image">';
										echo '<a href="' . get_permalink($post->ID) . '" >';
											the_post_thumbnail('thumbnail');
										echo '</a>';
										echo '</div>';
									}
									?>	
									
									<!-- Display Metadata -->
									<?php
									if( $meta_toggle == 1 )
									{ ?>
										<div class="magazine-metadata">
											<?php echo "Published on "; ?>
											<a href="<?php the_permalink() ?>"><?php echo get_the_date(); ?></a>
											<?php
											echo " by "; the_author_posts_link();
											echo " in "; the_category(', ');
											?>
										</div>
									<?php	
									}
									?>
			
									<div class="entry">
										<?php 
										add_filter('excerpt_more', 'cyberchimps_featured_post_excerpt_more');
										add_filter( 'excerpt_length', 'cyberchimps_featured_post_length', 999 );
										the_excerpt();
										remove_filter('excerpt_more', 'cyberchimps_featured_post_excerpt_more');
										remove_filter( 'excerpt_length', 'cyberchimps_featured_post_length', 999);
										?>
									</div><!--end entry-->  
								
									<div id="comments">
										<span class="comments-n-views"><?php comments_popup_link('No Comment', '1 Comment', '% Comments');?></span>
									</div>
								</div><!--end post_class-->
							</div><!--end post container-->
							<?php 
							$counter_box++;
							$counter_post++;
							if($column_no == $counter_box) {
								echo '</div>';

								// Add another "row-fluid" if more box posts exists.
								if( $counter_post < ( $row_no * $column_no ) )
									echo '<div class="row-fluid">';
								$counter_box = 0;
							}

							if( $counter_post == ( $row_no * $column_no ) ) {
							?>
								<!-- Start of wide posts -->
								<div class="row-fluid">	
							<?php
							}
						}
						else
						{ 
							if( ( $wide_post_toggle == 1 ) && ( $counter_wide < $wide_post_no ) )
							{
						?>
							<div class="post_container wide_post span12">
								<div <?php post_class() ?> id="post-<?php the_ID(); ?>">
								
									<!-- Display Title -->
									<h2 class="posts_title"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h2>
									
									<!-- Display Thumbnail -->
									<?php
									if ( has_post_thumbnail() && $featured_post_toggle ) {
										echo '<div class="featured-image">';
										echo '<a href="' . get_permalink($post->ID) . '" >';
											the_post_thumbnail('thumbnail');
										echo '</a>';
										echo '</div>';
									}
									?>
									
									<!-- Display Metadata -->
									<?php
									if( $meta_toggle == 1 )
									{ ?>
										<div class="magazine-metadata">
											<?php echo "Published on "; ?>
											<a href="<?php the_permalink() ?>"><?php echo get_the_date(); ?></a>
											<?php
											echo " by "; the_author_posts_link();
											echo " in "; the_category(', ');
											?>
										</div>
									<?php	
									}
									?>
									
									<div class="entry">
										<?php 
										add_filter('excerpt_more', 'cyberchimps_featured_post_excerpt_more');
										add_filter( 'excerpt_length', 'cyberchimps_magazine_post_wide', 999 );
										the_excerpt();
										remove_filter('excerpt_more', 'cyberchimps_featured_post_excerpt_more');
										remove_filter( 'excerpt_length', 'cyberchimps_magazine_post_wide', 999 );
										?>
									</div><!--end entry-->  
									
									<div id="comments">
										<span class="comments-n-views"><?php comments_popup_link('No Comment', '1 Comment', '% Comments');?></span>
									</div>	
								</div><!--end post_class-->
							</div><!--end post container-->
						<?php 
							$counter_wide++;
							}
						}
					}
				}	
				else {
					echo "<h2>Not Found</h2>";
				}?>	
			</div><!--end of wide posts -->

			<!-- Display pagination. -->
			<div class="row-fluid span6">
				<?php do_action( 'magazine_after_content', $magazine->max_num_pages ); ?>
			</div>
		</div>
		
		<!-- Add sidebar -->
		<?php get_sidebar( 'right' ); ?>
	</div>
<?php	
}

// Pagination
function cyberchimps_magazine_pagination( $num_pages ) {
	global $wp_query, $wp_rewrite;
	
	$wp_query->query_vars['paged'] > 1 ? $current = $wp_query->query_vars['paged'] : $current = 1;
	$pagination = array(
		'base' => @add_query_arg('paged','%#%'),
		'format' => '',
		'total' => $num_pages,
		'current' => $current,
		'show_all' => false,
		'end_size' => 1,
		'mid_size' => 2,
		'prev_text' => 'Prev',
		'next_text' => 'Next',
		'type' => 'array'
	);

	if ( $wp_rewrite->using_permalinks() )
		$pagination['base'] = user_trailingslashit( trailingslashit( remove_query_arg( 's', get_pagenum_link( 1 ) ) ) . 'page/%#%/', 'paged' );

	if ( !empty($wp_query->query_vars['s']) )
		$pagination['add_args'] = array( 's' => get_query_var( 's' ) );

	$pagination = paginate_links( $pagination );
	
	if ( is_array( $pagination ) ) {
		echo '<div class="pagination">';
		echo '<ul>';
		foreach( $pagination as $pag ) {
			/*if ( strpos( $pag, 'dots' ) != false ) {
				continue;
			} else*/ if ( strpos( $pag, 'current' ) != false ) {
				$num = preg_replace("/[^0-9]/", '', $pag);
				echo '<li class="active"><a>'.$num.'</a></li>';
			} else {
				echo '<li>'.$pag.'</li>';
			}
		}
		echo '</ul>';
		echo '</div>';
	}
}
add_action( 'magazine_after_content', 'cyberchimps_magazine_pagination' );
?>