<?php
/**
 * Portfolio element
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

if ( !class_exists( 'CyberChimpsPortfolio' ) ) {
	class CyberChimpsPortfolio {
		
		protected static $instance;
		public $options;
		
		/* Static Singleton Factory Method */
		public static function instance() {
			if (!isset(self::$instance)) {
				$className = __CLASS__;
				self::$instance = new $className;
			}
			return self::$instance;
		}	
		
		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct( ) {
			$this->options = get_option( 'cyberchimps_options' );
			add_action( 'init', array( $this, 'cyberchimps_init_portfolio_post_type' ) );
			add_action( 'portfolio_pro', array( $this, 'render_display' ) );
		}
		
		//Define Custom post type
		function cyberchimps_init_portfolio_post_type() {
			register_post_type( 'portfolio_images',
				array(
					'labels' => array(
						'name' => __('Portfolio', 'cyberchimps' ),
						'singular_name' => __('Images', 'cyberchimps' )
					),
					'public' => true,
					'show_ui' => true, 
					'supports' => array('custom-fields', 'title'),
					'taxonomies' => array( 'portfolio_cats'),
					'has_archive' => true,
					'menu_icon' => get_template_directory_uri() . '/cyberchimps/lib/images/custom-types/portfolio.png',
					'rewrite' => array('slug' => 'portfolio')
				)
			);
			
			$labels = array(
				'name' => _x( 'Portfolio Categories', 'taxonomy general name', 'cyberchimps' ),
				'singular_name' => _x( 'Portfolio Catergory', 'taxonomy singular name', 'cyberchimps' ),
				'search_items' =>  __( 'Search Portfolio', 'cyberchimps' ),
				'all_items' => __( 'All Portfolios', 'cyberchimps' ),
				'parent_item' => __( 'Portfolio Category', 'cyberchimps' ),
				'parent_item_colon' => __( 'Portfolio Category:', 'cyberchimps' ),
				'edit_item' => __( 'Edit Portfolio Category', 'cyberchimps' ), 
				'update_item' => __( 'Update Portfolio Category', 'cyberchimps' ),
				'add_new_item' => __( 'Add New Portfolio Category', 'cyberchimps' ),
				'new_item_name' => __( 'New Portfolio Category Name', 'cyberchimps' ),
				'menu_name' => __( 'Portfolio Category', 'cyberchimps' )
			); 	
			register_taxonomy( 'portfolio_cats', array('portfolio_images'), array(
				'public' => true,
				'show_in_nav_menus' => false,
				'hierarchical' => true,
				'labels' => $labels,
				'show_ui' => true
			));
			
			$meta_boxes = array();
			
			$mb = new Chimps_Metabox('Portfolio', 'Portfolio Element', array('pages' => array('portfolio_images')));
			$mb
				->tab( __( 'Portfolio Element', 'cyberchimps' ) )
					->single_image('portfolio_image', __( 'Portfolio Image', 'cyberchimps' ), '')
					->text('caption_text', __( 'Caption', 'cyberchimps' ), '')
					->checkbox('portfolio_lightbox_toggle', __( 'Lightbox', 'cyberchimps' ), '', array('std' => 'on'))
					->checkbox('custom_portfolio_url_toggle', __( 'Custom Portfolio URL', 'cyberchimps' ), '', array('std' => 'off'))
					->text('custom_portfolio_url', __( 'URL', 'cyberchimps' ), '')
				->end();
				
			foreach ($meta_boxes as $meta_box) {
				$my_box = new RW_Meta_Box_Taxonomy($meta_box);
			}
		}

		public function render_display() {
			global $post;
			if( is_page() ) {
				$images_per_row = get_post_meta( $post->ID, 'portfolio_row_number', true );
				$portfolio_category = get_post_meta( $post->ID, 'portfolio_category', true );
				$portfolio_title_toggle = get_post_meta( $post->ID, 'portfolio_title_toggle', true );
				$portfolio_title = get_post_meta( $post->ID, 'portfolio_title', true );
			}
			else {
				$images_per_row = $this->options['cyberchimps_blog_portfolio_pro_per_row'];
				$customcategory_obj = ( isset( $this->options['cyberchimps_blog_portfolio_pro_category'] ) ) ? get_term( $this->options['cyberchimps_blog_portfolio_pro_category'], 'portfolio_cats' ) : '';
				$portfolio_category = ( isset( $this->options['cyberchimps_blog_portfolio_pro_category'] ) ) ? $customcategory_obj->slug : '';
				$portfolio_title_toggle = $this->options['cyberchimps_blog_portfolio_pro_title'];
				$portfolio_title = $this->options['cyberchimps_blog_portfolio_pro_title_text'];
			}
			$args = array(
							'numberposts'     => 500,
							'offset'          => 0,
							'portfolio_cats'	=> $portfolio_category,
							'orderby'         => 'post_date',
							'order'           => 'ASC',
							'post_type'       => 'portfolio_images',
							'post_status'     => 'publish'
							);
			$portfolio_posts = get_posts( $args );
			
			$port_array = array();
			$i = 1;
			switch( $images_per_row ) {
				case 2:
					$span = 'span6';
					break;
				case 3:
					$span = 'span4';
					break;
				case 4:
					$span = 'span3';
					break;
			}?>
      <div id="portfolio" class="row-fluid">
     	 <div id="gallery" class="span12">
       <?php
			 	// check if there are any posts retrieved and if not display default images
				if( !empty( $portfolio_posts ) ): ?>
          <?php if( $portfolio_title_toggle && $portfolio_title != '' ): ?>
          	<h2><?php echo $portfolio_title; ?></h2>
          <?php endif; ?>
					<?php foreach( $portfolio_posts as $port ):
          
			// Getting portfolio options
            $image			 = get_post_meta( $port->ID, 'portfolio_image', true );
            $caption		 = ( get_post_meta( $port->ID, 'caption_text', true ) != '' ) ? get_post_meta( $port->ID, 'caption_text', true ) : get_the_title( $port->ID );
            $link			 = get_post_meta( $port->ID, 'custom_portfolio_url', true );
            $link_use		 = get_post_meta( $port->ID, 'custom_portfolio_url_toggle', true );
			$lightbox_toggle = get_post_meta( $port->ID, 'portfolio_lightbox_toggle', true );
			
			// Setting link for custom URL and rel for lightbox
            $url = ( ( $lightbox_toggle == 0 ) && ( $link_use == 1 ) && ( $link != '' ) ) ? $link : $image;
            $rel = ( $lightbox_toggle == 1 ) ? 'rel="cyberchimps-lightbox"' : '';
            
            if( $i == 1 ): ?>
              <ul class="row-fluid">
            <?php endif;
            if( $i <= $images_per_row ): ?>
              <li id="portfolio_wrap" class="<?php echo $span; ?>">
                <div class="portfolio_item">
                <a href="<?php echo $url; ?>" <?php echo $rel; ?> title="<?php echo $caption; ?>">
                  <img src="<?php echo $image ;?>" alt="<?php echo $caption; ?>"/>
                  <div class="portfolio_caption"><?php echo $caption; ?></div>
                </a>
                </div>
              </li><!-- #portfolio_wrap -->
            <?php endif;
            if( $i == $images_per_row ) {
              $i = 1;
              echo '</ul>';
            }
            else {
              $i++;
            }
          
          endforeach; 
					
					// if there are no posts then display defaults
					else:
						$image = get_template_directory_uri(). "/cyberchimps/lib/images/portfolio.jpg";
					?>
          <h2>Portfolio</h2>
          
          <ul class="row-fluid">
          	<li id="portfolio_wrap" class="span3">
              <div class="portfolio_item">
                <a href="<?php echo $image; ?>" rel="cyberchimps-lightbox" title="Caption">
                <img src="<?php echo $image; ?>" alt="CyberChimps"/>
                <div class="portfolio_caption">CyberChimps Portfolio</div>
              </a>
              </div>
            </li><!-- #portfolio_wrap -->
            
            <li id="portfolio_wrap" class="span3">
              <div class="portfolio_item">
                <a href="<?php echo $image; ?>" rel="cyberchimps-lightbox" title="Caption">
                <img src="<?php echo $image; ?>" alt="CyberChimps"/>
                <div class="portfolio_caption">CyberChimps Portfolio</div>
              </a>
              </div>
            </li><!-- #portfolio_wrap -->
            
            <li id="portfolio_wrap" class="span3">
              <div class="portfolio_item">
                <a href="<?php echo $image; ?>" rel="cyberchimps-lightbox" title="Caption">
                <img src="<?php echo $image; ?>" alt="CyberChimps"/>
                <div class="portfolio_caption">CyberChimps Portfolio</div>
              </a>
              </div>
            </li><!-- #portfolio_wrap -->
            
            <li id="portfolio_wrap" class="span3">
              <div class="portfolio_item">
                <a href="<?php echo $image; ?>" rel="cyberchimps-lightbox" title="Caption">
                <img src="<?php echo $image; ?>" alt="CyberChimps"/>
                <div class="portfolio_caption">CyberChimps Portfolio</div>
              </a>
              </div>
            </li><!-- #portfolio_wrap -->
          </ul>
          <?php endif; ?>
      
      		</div><!-- #gallery .span12-->
			</div><!-- row-fluid -->
							
			<?php
		}
	}
}
CyberChimpsPortfolio::instance();